# Generated by Django 4.0.3 on 2022-04-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
