# Generated by Django 4.0.3 on 2022-04-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_post_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
