# Generated by Django 4.0.3 on 2022-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
