# Generated by Django 4.0.3 on 2022-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='magen',
            new_name='imagen',
        ),
    ]
