# Generated by Django 4.0.3 on 2022-04-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Singup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Singup',
        ),
    ]
